### ISSUE TITLE
Pan & zoom not working for x-axis

### ISSUE THREAD

**Issue by Intelli32** [chartjs/chartjs-plugin-zoom#8] opened 2016-06-01 10:50 UTC
Hi, I am trying to get pan & zoom working but I am not able to do that on X-axis even though I have the following settings. The provided examples works fine and I am trying to mimic those.

`pan: {
        enabled: true,
    mode: 'xy'
    limits: {
          max: 10,
          min: 0.5
    }
 },`

`zoom: {
        enabled: true,
    mode: 'xy'
    limits: {
          max: 10,
          min: 0.5
    }
 },`

What are the common mistakes when this happens?
Fiddle: https://jsfiddle.net/jm1adysp/3/

**Comment by etimberg** [comment] 2016-06-01 11:03
@Intelli32 can you post a fiddle?

**Comment by Intelli32** [comment] 2016-06-01 11:36
Sorry, I thought I would have time to add a fiddle but you replied so fast :) Updated my post

**Comment by etimberg** [comment] 2016-06-01 12:23
Awesome, thanks. To get this working, I need to implement panning and zooming for the category scale. Right now only numerical scales are supported

**Comment by Intelli32** [comment] 2016-06-01 12:27
Ok, but I get the same result even if I change labels to [1, 2, 3, 4, 5]. But maybe this was not what you meant with "numerical scale"?

**Comment by etimberg** [comment] 2016-06-01 12:47
I meant using a linear, logarithmic, or time type of scale for the x axis.

**Comment by Intelli32** [comment] 2016-06-01 14:03
My intention was actually to use a time scale so I got it working with that now. Thanks for the quick response!

**Comment by beefo** [comment] 2016-08-11 13:21
@etimberg I'm having a similar issue with panning using "time" scale x axis. I created a [plunker here](https://plnkr.co/edit/1OcgkwR2nUMqDkoK6jNl?p=preview) with an example.

**Comment by beefo** [comment] 2016-09-02 19:47
@etimberg Is sample I provided adequate? Were you able to reproduce?

**Comment by etimberg** [comment] 2016-09-02 20:18
@beefo just had a look now. I think you need to include hammerjs to make this work

**Comment by beefo** [comment] 2016-09-06 18:07
Ah, yes, thank you @etimberg. Worked like a charm.

**Comment by ivansabik** [comment] 2016-09-08 18:12
Related question, sorry for asking here but it's related and I solved part of my issue with this. Zoom is now working properly by specifying the `type` for scale. Pan is not working, does this actually work with Line? I saw example with Scatter.

Here's my code extract, could also do fiddle or plunker:

```
        var chartOptions = {
          scaleShowGridLines: true,
          scaleGridLineColor: "rgba(0,0,0,.05)",
          scaleGridLineWidth: 1,
          scaleShowHorizontalLines: true,
          scaleShowVerticalLines: true,
          responsive: true,
          maintainAspectRatio: false,
          pan: {
              enabled: true,
              mode: 'xy'
          },
          zoom: {
              enabled: true,
              mode: 'xy'
          },
          scales: {
              xAxes: [{
                  type: 'time'
              }],
              yAxes: [{
                  type: 'linear'
              }]
          }
        };
        var lineChartCanvas = $("#lineChart").get(0).getContext("2d");
        var lineChart = Chart.Line(lineChartCanvas, {data: chartData, options: chartOptions})
```

Thanks, great project

**Comment by ivansabik** [comment] 2016-09-23 17:59
Hey guys just for the record and if anyone finds useful, my code works now for panning and zoomig. Panning wasn't working due to stupid HTML type when importing Hammer.js, was using `<script scr=` instead of `<script src=` 😵 

Answering my question: It does work with Line as well as scatter and other examples provided

**Comment by quique1233** [comment] 2017-01-13 20:27
@etimberg 

> Awesome, thanks. To get this working, I need to implement panning and zooming for the category scale. Right now only numerical scales are supported 

Any new about this?

**Comment by Koshux** [comment] 2017-05-08 15:27
@etimberg 
I also am finding weird behaviour in the following codepen:
http://codepen.io/anon/pen/VbyZpL

This was the initial codepen I had found however tried addressing the solutions mentioned across the issues in this GitHub page however I still could not get it to work.  

The bug/unwanted behaviour I find is that it appears that panning occurs on the opposite side of where the mouse pointer coordinates exist.  Meaning if I place my cursor on the left-most side of the chart, it pans to the right-most side, whereas if I place my cursor on the right-most side of the chart, it pans to the left-most side of the chart.

**Comment by RPHolloway** [comment] 2017-05-29 15:39
@Koshux I am seeing the same issue, and it seems to zoom in, to only show the graph region between two points. I was expecting it to work like panning in the y direction (which works great!).

Did you ever find an answer to this problem?

**Comment by Koshux** [comment] 2017-05-30 07:13
@RPHolloway I have not yet found a solution for it unfortunately.  I have been impeded by further progress also due to #73 .

**Comment by adeel3612** [comment] 2017-06-29 15:20
anyone find the solution for panning on the x-axis.?

**Comment by adeel3612** [comment] 2017-07-13 13:24
@RPHolloway @Koshux  guys any thing you got for the category scale? any hack or idea ?

**Comment by mcelotti** [comment] 2018-03-20 10:46
Hi @adeel3612 I was having the same problem, take e a look at #109

**Comment by JamesMcMahon** [comment] 2020-11-10 22:58
> Awesome, thanks. To get this working, I need to implement panning and zooming for the category scale. Right now only numerical scales are supported

Is this statement still true?

**Comment by kurkle** [comment] 2021-03-08 21:27
Its been implemented years ago, closing.

**Closed by kurkle** 2021-03-08 21:27 UTC
Labels: enhancement
