### ISSUE TITLE
Limit Zoom In with Time scale (v 0.80)

### ISSUE THREAD

**Issue by devenbj** [chartjs/chartjs-plugin-zoom#227] opened 2019-03-25 02:27 UTC
Just started using chart.js today. Was unable to limit zooming in on time scale (using sample zoom-time.html file).

Setting rangeMax and rangeMin only worked when set to time min and max values. When done, this correctly prevented zooming out beyond the data set.

It still let me Zoom in as far as I wanted. I want to limit zooming in. I was able to accomplish this by adding a single line in the chartjs-plugin-zoom.js file... And creating a corresponding option in the HTML file "maxZoom", which works with Unix timestamp values.

I've not contributed to GitHub in the past,and do not know how to do a pull request. I am pasting the new line below, with the line above and below from the source.

function zoomTimeScale(scale, zoom, center, zoomOptions) {
	if(scale.max - scale.min < zoomOptions.maxZoom && zoom>1) zoom=1;
	zoomNumericalScale(scale, zoom, center, zoomOptions);

**Comment by flaushi** [comment] 2019-04-18 09:17
I encounter a related issue, but I think it is tied to the plugin-annotations.
Can you check if you see the [same error](https://github.com/chartjs/chartjs-plugin-annotation/issues/158)?

**Comment by devenbj** [comment] 2019-04-18 13:23
I'm not using the plugin-annotations. Only using the plugin-zoom.

**Comment by nullifiedtsk** [comment] 2020-03-03 00:16
Agree, looks like there is no way to limit timescale without modifying source code.
There should be a hook like `allowZoom` or `onBeforeZoom`.

Created a pull-request to demonstrate you this issue:
e.g. https://github.com/chartjs/chartjs-plugin-zoom/pull/329

It may be used this way:
```
chart.options: {
  ...
  
  zoom: {
    ...this.baseOptions.zoom,
    rangeMin: { x: minDateValue },
    rangeMax: { x: maxDateValue },
    allowZoom: (chart, scale, beforeZoom, changes) => {
      if (scale.id === 'x-axis-0') {
        const msToSecondsDelimeter = 1024 * 60;
        const totalSecondsInViewBeforeZoom = (beforeZoom.ticks.max - beforeZoom.ticks.min) / msToSecondsDelimeter;
        const totalSecondsInViewAfterZoom = (changes.ticks.max - changes.ticks.min) / msToSecondsDelimeter;
        if (totalSecondsInViewAfterZoom < 60 && totalSecondsInViewAfterZoom <= totalSecondsInViewBeforeZoom) {
        return false;
        }
      }
      return true;
    }
  }
  
  ...
}
```

p.s. Feel free to merge, comment or refuse it :)

May we missed something simple that allows us to limit MAX zoom value ?

p.p.s. It also may be nice to limit zoom by minUnit/maxUnit for time scales, but it looks there is no way to implement such kind of behavior without accessing private chartjs methods or calling chart.update twice (to recalculate current axis time unit).

**Comment by sabres207** [comment] 2020-12-24 16:02
@nullifiedtsk any news regarding the allowZoom pull request?

**Comment by etimberg** [comment] 2021-04-25 16:13
Duplicate of #112

**Closed by etimberg** 2021-04-25 16:13 UTC
Labels: enhancement
