### ISSUE TITLE
Font color canvas changes on zoom

### ISSUE THREAD

**Issue by DSC-CSTS** [chartjs/chartjs-plugin-zoom#449] opened 2021-04-14 15:03 UTC
The axis of my chart have a blue color. As soon as zoom is used, the font color changes to grey. When using resetZoom, the color doesn't change back to it's original (and desired) color. Is this a bug?

Best regards,
Dirk

**Comment by jledentu** [comment] 2021-04-14 16:45
I can't reproduce your issue. Which version are you using? Can you provide your chart configuration or, even better, a fiddle... ?

**Comment by kurkle** [comment] 2021-04-14 17:11
Are you possibly using some other plugins too?

**Comment by DSC-CSTS** [comment] 2021-04-15 07:00
@jledentu   It's all part of a Vue application with the following versions:

"chart.js": "^2.9.3",
chartjs-plugin-zoom": "^0.7.7",
vue": "^2.6.11",
vue-chartjs": "^3.5.0",

I will try to put together a fiddle (will be my first) but attached the config of the chart. 
[chartline.zip](https://github.com/chartjs/chartjs-plugin-zoom/files/6315744/chartline.zip)

@kurkle Yes, there are more plugins used like jointjs, vguage.

**Comment by kurkle** [comment] 2021-04-28 12:15
Fixed your fiddle, but don't see the issue: https://jsfiddle.net/b2artsmn/

**Comment by kurkle** [comment] 2021-05-16 06:00
closing as we can not reproduce this.

**Closed by kurkle** 2021-05-16 06:00 UTC
Labels: bug, needs test case
