### ISSUE TITLE
Error in wheel function on Zoom

### ISSUE THREAD

**Issue by aschurg** [chartjs/chartjs-plugin-zoom#480] opened 2021-04-29 20:21 UTC
My console is showing a ton of errors every time I zoom. I have tried 1.0.0-beta.3 and 1.0.0-beta.2.

With beta.3 I get this error:

<img width="411" alt="Screen Shot 2021-04-29 at 2 15 52 PM" src="https://user-images.githubusercontent.com/25371301/116612998-69c67600-a8f5-11eb-89a2-0295bdc9b581.png">

The zoom still appears to work, but my onZoomComplete callback is never triggered. Also, panning is working fine!

zoomOptions look like this:

```javascript
const zoomOptions = {
	limits: {
		x: { min: max_range.x.min, max: max_range.x.max },
		y: { min: max_range.y.min, max: max_range.y.max }
	},
	pan: {
		enabled: true,
		threshold: 10,
		onPan: this.interuptPanZoom,
		onPanComplete: this.onPanZoom
	},
	zoom: {
		enabled: true,
		drag: false,
		mode: 'xy',
		sensitivity: 3,
		threshold: 2,
		speed: 0.05,
		onZoom: this.interuptPanZoom,
		onZoomComplete: this.onPanZoom
	}
};
```

Any ideas on how to get this working?

**Comment by kurkle** [comment] 2021-05-02 13:51
Maybe trying to use with chart.js v2 that does not call the `start` hook at all?

**Comment by kurkle** [comment] 2021-05-16 06:00
closing because we can not reproduce this without a test case.

**Closed by kurkle** 2021-05-16 06:00 UTC
Labels: needs test case
