### ISSUE TITLE
adjusting zoom using function call

### ISSUE THREAD

**Issue by mani76** [chartjs/chartjs-plugin-zoom#378] opened 2020-08-19 08:16 UTC
Hello, Is it possible to also adjust zoom level using function call?
I would like to create own buttons which can be used to zoom in and out.

**Comment by jledentu** [comment] 2021-04-16 10:17
I close this issue since it's a duplicate of #43, you'll find some answers there and in #123.

**Closed by jledentu** 2021-04-16 10:17 UTC
Labels: duplicate
