### ISSUE TITLE
Drag zoom loosing data points

### ISSUE THREAD

**Issue by jordanpapaleo** [chartjs/chartjs-plugin-zoom#52] opened 2016-11-02 00:07 UTC
Hi

I am working on an implementation of the zoom plugin using the drag feature.  I am following the `samples/zoom-time.html` example.  When i drag a zoom area, the resulting line chart looses data points.  This happens in both my chart and the example chart.

Drag:

![screen shot 2016-11-01 at 4 56 34 pm 2](https://cloud.githubusercontent.com/assets/1728807/19911979/711cc69c-a054-11e6-8b8a-bb5a86996cc2.png)

Result:

![screen shot 2016-11-01 at 4 56 40 pm](https://cloud.githubusercontent.com/assets/1728807/19911983/78c06cb4-a054-11e6-9775-6f796647e885.png)

As you can see the first data point is gone and the resulting chart is off too.  The result in mine is even more extreme with more of a flattening line.  It kind of looks like the chart data is averaged instead of zoomed.  

Here is the zoom config I am using: 

```js
zoom: {
  enabled: true,
  drag: true,
  mode: 'x',
  limits: {
    max: 10,
    min: 0.5
  }
}
```

limits was in the example but I do not see in in chart.zoom.js

I'd love some help here :)

Thanks,

Jordan

**Comment by etimberg** [comment] 2016-11-02 00:39
I think the flattening is coming from how the bezier control points are calculated. We'll need to do some investigation to figure out why the points are lost. My likely theory is that the zoom is incorrectly calculated and the first point is now outside the new axis minimum

**Comment by Bakirelived** [comment] 2017-01-06 11:52
hey. You have any progress on this? is there somewhere you may need help? My team has this bug as well and if we could we would like to help it be solved asap

**Comment by etimberg** [comment] 2017-01-06 13:09
Hey, i haven't looked into this more yet. Do you have an example that reproduces for debugging?

**Comment by Bakirelived** [comment] 2017-01-06 18:51
I think the original post was made with an example from the demo, still, if
you want I can provide a new one

**Comment by marco-silva0000** [comment] 2017-05-02 09:39
do you need any help moving this forward?

**Comment by marco-silva0000** [comment] 2017-06-30 16:03
any progress on this?

**Comment by jface78** [comment] 2017-10-09 18:55
Same issue here.

**Comment by CalvinChhour** [comment] 2017-10-10 15:13
Noticing this issue as well.

**Comment by jonathanface** [comment] 2017-11-07 16:30
I have put together a fiddle to illustrate this issue: https://jsfiddle.net/opr9rgo6/

In my case it occurs within a time chart - not sure if the issue is specific to time or not, but I see the first cited example is also a time chart.

Also I notice that for some reason the tooltip for the first point coordinate is invalid date - not sure why, or if relevant.

To see the issue dragover a section which includes the first 2 data points like so:
![prezoom](https://user-images.githubusercontent.com/30864098/32504689-73034674-c3ae-11e7-8df7-512860586209.png)

You will see the zoomed content does not include the first data point:
![postzoom](https://user-images.githubusercontent.com/30864098/32504766-9c8648f2-c3ae-11e7-84c2-87ac04eb0e60.png)

Also, for this fiddle I used chart bundle 2.5, since zoom doesn't work at all with more recent versions.

**Comment by Skuhoo** [comment] 2018-01-21 07:35
Any progress on this? I tried looking into it awhile back but had no luck.

**Comment by benmccann** [comment] 2018-01-22 16:38
Have you tried again with the latest version 0.6.2 which has many fixes included?

**Comment by Skuhoo** [comment] 2018-01-23 08:01
@benmccann Just tried the latest version and the issue is still there, unchanged.

The issue is that the zoomed scale it calculates from the selection is incorrect unless the center of the selection is at the center of the chart. The farther away the center of the selection is from the center of the chart, the more inaccurate the zoomed scale becomes.

**Comment by benmccann** [comment] 2018-01-23 18:25
Ok. I've been trying to merge PRs with fixes, but there's no one actively fixing bugs in this library. So really anyone who wants this fixed will have to send a PR

**Comment by chriser-** [comment] 2018-02-28 10:58
The usage of the zoom functions when using the drag selection is pretty stupid, there is already a good function to get the value at a pixel. I refactored the mouse up handler, and it works perfectly now with a time graph. I haven't tested it with non-time graphs, but it should work exactly the same.

```
     chartInstance.zoom._mouseUpHandler = function(event){
        if (chartInstance.zoom._dragZoomStart) {
          helpers.each(chartInstance.scales, function(scale, id) {
            if(scale.isHorizontal()) {
              var beginPoint = chartInstance.zoom._dragZoomStart;
              var offsetX = beginPoint.target.getBoundingClientRect().left;
              var startX = Math.min(beginPoint.clientX, event.clientX) - offsetX;
              var endX = Math.max(beginPoint.clientX, event.clientX) - offsetX;
              var limitObject = scale.options.type == 'time' ? scale.options.time : scale.options.ticks;
              limitObject.min = scale.getValueForPixel(startX);
              limitObject.max = scale.getValueForPixel(endX);
            }
          });
          chartInstance.zoom._dragZoomStart = null;
          chartInstance.zoom._dragZoomEnd = null;
        }
      };
```

If someone wants to submit a PR or fix it better, feel free to do so.

**Comment by JoshAudibert** [comment] 2018-04-04 15:35
I'm only using time graphs for drag-zoom, and @chriser-'s solution works great!

**Closed** 2019-01-24 15:19 UTC
Labels: bug
