### ISSUE TITLE
[BUG] 2.7.1 Zoom with DateTime and many y axes

### ISSUE THREAD

**Issue by rucin96** [chartjs/chartjs-plugin-zoom#128] opened 2018-02-06 12:22 UTC
If we have chart with many y axes (for example three) and many datasets (for example 1000) then zoom practically does not change the scale of the chart.

**How to resolve?**
Change zoomIndexScale function to
```
function zoomIndexScale(scale, zoom, center, zoomOptions) {
	var labels = scale.chart.data.labels;
	var minIndex = scale.minIndex;
	var lastLabelIndex = labels.length - 1;
	var maxIndex = scale.maxIndex;
	var sensitivity = zoomOptions.sensitivity;
	var chartCenter =  scale.isHorizontal() ? scale.left + (scale.width/2) : scale.top + (scale.height/2);
	var centerPointer = scale.isHorizontal() ? center.x : center.y;
	var scaleIndex = Math.floor((scale.maxIndex - scale.minIndex) / 5);

	zoomNS.zoomCumulativeDelta = zoom > 1 ? zoomNS.zoomCumulativeDelta + 1 : zoomNS.zoomCumulativeDelta - 1;

	if (Math.abs(zoomNS.zoomCumulativeDelta) > sensitivity){
		if(zoomNS.zoomCumulativeDelta < 0){
			if(centerPointer >= chartCenter){
				if (minIndex <= 0){
					maxIndex = Math.min(lastLabelIndex, maxIndex + scaleIndex);
				} else{
					minIndex = Math.max(0, minIndex - scaleIndex);
				}
			} else if(centerPointer < chartCenter){
				if (maxIndex >= lastLabelIndex){
					minIndex = Math.max(0, minIndex - scaleIndex);
				} else{
					maxIndex = Math.min(lastLabelIndex, maxIndex + scaleIndex);
				}
			}
			zoomNS.zoomCumulativeDelta = 0;
		}
		else if(zoomNS.zoomCumulativeDelta > 0){
			if(centerPointer >= chartCenter){
				minIndex = minIndex < maxIndex ? minIndex = Math.min(maxIndex, minIndex + scaleIndex) : minIndex;
			} else if(centerPointer < chartCenter){
				maxIndex = maxIndex > minIndex ? maxIndex = Math.max(minIndex, maxIndex - scaleIndex) : maxIndex;
			}
			zoomNS.zoomCumulativeDelta = 0;
		}
		scale.options.ticks.min = rangeMinLimiter(zoomOptions, labels[minIndex]);
		scale.options.ticks.max = rangeMaxLimiter(zoomOptions, labels[maxIndex]);
	}
}
```

**Comment by benmccann** [comment] 2019-04-14 14:55
This sounds like a duplicate of https://github.com/chartjs/chartjs-plugin-zoom/issues/127

**Closed by benmccann** 2019-04-14 14:55 UTC
