### ISSUE TITLE
Zoom & Pan do not work, but the callbacks are fired

### ISSUE THREAD

**Issue by tieftontier** [chartjs/chartjs-plugin-zoom#353] opened 2020-05-09 16:49 UTC
Hi there,

I can not get zoom or pan functionality working. I think I have read everything i could find about it and tried out a lot of things. So any help here is greatly appreciated!

The strange behaviour is, that i get the callbacks if I try zooming or panning, like
```
              // Function called while the user is zooming
              onZoom: function({chart}) { 
                console.log(`I'm zooming!!!`); 
                console.log(chart);
              },
              // Function called once zooming is completed
              onZoomComplete: function({chart}) { console.log(`I was zoomed!!!`); }
```

But it does not zoom or pan.

Here is my code so far:

```
import { Component, OnDestroy, HostListener } from '@angular/core';
import { NbThemeService, NbColorHelper, NbButtonModule } from '@nebular/theme';
import { RoomData } from '../data/room-data';
import { DataService } from '../service/data.service';
import 'hammerjs';
import 'chartjs-plugin-zoom';

@Component({
  selector: 'chart-line-iaq',
  styleUrls: ['./chartjs-line.component.scss'],
  template: `
    <button nbButton outline status="info" size="medium" (click)="getData($event)">get data</button>
    <p></p>
    <chart type="line" [data]="data" [options]="options"></chart>
  `,
})

export class IaqChartjsLineComponent implements OnDestroy {
  data: any;
  options: any;
  themeSubscription: any;
  public Roomlist: RoomData[];
  sensor_avg: number[];  
  roomNames: string[];  
  sensor_timestamp;
  json: any;

  constructor(private theme: NbThemeService, private data_Rest: DataService) {  }

  ngOnDestroy(): void {
    this.themeSubscription.unsubscribe();
  }

  public getData(event: any): void{
    this.themeSubscription = this.theme.getJsTheme().subscribe(config => {

      const colors: any = config.variables;
      const chartjs: any = config.variables.chartjs;


      // data service passes an observable with the rest response data
      let obs = this.data_Rest.getMessage('iaq');

      // subscribe on data from rest response as it comes async
      obs.subscribe((data) => {

        this.json=data;  

        // init data object for visualizing the chart
        this.data=[];
        this.data.labels=[];
        this.data.datasets=[];
        this.data.datasets.data=[];
        this.data.datasets.label ='';

        // init temp variables to fill the chart data
        this.Roomlist=[];
        this.sensor_avg = [];
        this.sensor_timestamp = [];
        this.roomNames = [];
        let istimestampset = false;   

        // fill the list of rooms with rooms from database response
        for(let room of this.json.aggregations.terms_name.buckets){
          this.Roomlist.push(new RoomData(room));
          this.Roomlist[this.Roomlist.length-1].setIaqData(room);
        }

        // fill the labels with all timestamps
        for(let room of this.Roomlist){
          for(let value of room.iaqData)
          {
            if(this.sensor_timestamp.indexOf(value.timestamp) == -1)
              this.sensor_timestamp.push(value.timestamp);
          }
        }
        // sort timestamp array
        this.sensor_timestamp.sort((a, b) => new Date(b.CREATE_TS).getTime() - new Date(a.CREATE_TS).getTime());
        for(let timestamp of this.sensor_timestamp){
          this.data.labels.push(timestamp);
        }
          
        // fill chart data
        for(let room of this.Roomlist){
          for(let value of room.iaqData)
          {
            // as long as the right timestamp is not reached "null" is added to array.
            while(this.data.labels.indexOf(value.timestamp) > this.sensor_avg.length)
            {
              this.sensor_avg.push(null);
            }
            this.sensor_avg.push(value.avg);
            
          }
          istimestampset = true;

          // create random color hex code
          var randomColor = '#'+'0123456789abcdef'.split('').map(function(v,i,a){return i>5 ? null : a[Math.floor(Math.random()*16)] }).join('');

          // push data to the chart
          this.data.datasets.push({
            data: this.sensor_avg,
            label: room.roomName,
            backgroundColor: NbColorHelper.hexToRgbA(randomColor, 0.3),
            borderColor: randomColor,
            hidden: true 
          });

          // clear the data array for the next room.
          this.sensor_avg = [];
        }    
      });

      //////////////////////////////////////////////
      // options of chartjs visualization
      this.options = {
        responsive: true,
        maintainAspectRatio: true,
        scales: {
          xAxes: [
            {
              gridLines: {
                display: true,
                color: chartjs.axisLineColor,
              },
              ticks: {
                fontColor: chartjs.textColor,
              },
            },
          ],
          yAxes: [
            {
              gridLines: {
                display: true,
                color: chartjs.axisLineColor,
              },
              ticks: {
                fontColor: chartjs.textColor,
                min: 0,
                max: 250,
                stepSize: 50
              },
            },
          ],
        },
        legend: {
          labels: {
            fontColor: chartjs.textColor,
          },
        },
        plugins: {
          zoom: {
            // Container for pan options
            pan: {
              // Boolean to enable panning
              enabled: true,
        
              // Panning directions. Remove the appropriate direction to disable
              // Eg. 'y' would only allow panning in the y direction
              // A function that is called as the user is panning and returns the
              // available directions can also be used:
              //   mode: function({ chart }) {
              //     return 'xy';
              //   },
              mode: 'xy',
        
              rangeMin: {
                // Format of min pan range depends on scale type
                x: null,
                y: null
              },
              rangeMax: {
                // Format of max pan range depends on scale type
                x: null,
                y: null
              },
        
              // On category scale, factor of pan velocity
              speed: 20,
        
              // Minimal pan distance required before actually applying pan
              threshold: 10,
        
              // Function called while the user is panning
              onPan: function({chart}) { console.log(`I'm panning!!!`); },
              // Function called once panning is completed
              onPanComplete: function({chart}) { console.log(`I was panned!!!`); }
            },
        
            // Container for zoom options
            zoom: {
              // Boolean to enable zooming
              enabled: true,
        
              // Enable drag-to-zoom behavior
              drag: false,
        
              // Drag-to-zoom effect can be customized
              // drag: {
              // 	 borderColor: 'rgba(225,225,225,0.3)'
              // 	 borderWidth: 5,
              // 	 backgroundColor: 'rgb(225,225,225)',
              // 	 animationDuration: 0
              // },
        
              // Zooming directions. Remove the appropriate direction to disable
              // Eg. 'y' would only allow zooming in the y direction
              // A function that is called as the user is zooming and returns the
              // available directions can also be used:
              //   mode: function({ chart }) {
              //     return 'xy';
              //   },
              mode: 'xy',
        
              // rangeMin: {
              //   // Format of min zoom range depends on scale type
              //   x: null,
              //   y: null
              // },
              // rangeMax: {
              //   // Format of max zoom range depends on scale type
              //   x: null,
              //   y: null
              // },
        
              // Speed of zoom via mouse wheel
              // (percentage of zoom on a wheel event)
              speed: 0.1,
        
              // On category scale, minimal zoom level before actually applying zoom
              sensitivity: 3,
        
              // Function called while the user is zooming
              onZoom: function({chart}) { 
                console.log(`I'm zooming!!!`); 
                console.log(chart);
              },
              // Function called once zooming is completed
              onZoomComplete: function({chart}) { console.log(`I was zoomed!!!`); }
            }
          }
        }
      };
    });
  }
}
```

Thank you so much for any help!
Tom

**Comment by Luckino** [comment] 2020-05-11 13:24
Here is an example where zoom and pan on the x axis are applied, but only the zoom works.

https://plnkr.co/edit/ZpgRAHvfhmkKZJuk

**Comment by tieftontier** [comment] 2020-05-11 17:40
I tried a lot of stuff again today:
- x-axis of type : 'time'
- x-axis just with numerical values
- setting different min/max-values as ticks
- commenting different options to see if it changes the behaviour
- ...

I am really clueless, what I am doing wrong.

**Comment by tieftontier** [comment] 2020-05-19 09:55
Still nobody that can help me?

**Comment by etimberg** [comment] 2021-04-25 17:10
It's very hard to say what is wrong here. It sounds like there are no errors. Without a test case in a fiddle, it's hard to diagnose. I don't know angular so I can't convert this to a working reproduce.

**Comment by kurkle** [comment] 2021-05-01 14:34
Closing as a lot has changed since this and its very unlikely a test case is provided.

**Closed by kurkle** 2021-05-01 14:34 UTC
Labels: needs test case
