### ISSUE TITLE
Incorrect work while paning with zoom enabled

### ISSUE THREAD

**Issue by anton-shchyrov** [chartjs/chartjs-plugin-zoom#207] opened 2019-02-27 13:47 UTC
I create chart with pan limit and zoom enabled. When I panned chart it zooming with fix one border

Init code
```
new Chart(document.getElementById("chart"), {
    type: 'scatter',
    data: {
        datasets: [{
            showLine: true,
            data: [{
                x: -10, y: 0
            }, {
                x: 0, y: 10
            }, {
                x: 10, y: 5
            }]
        }]
    },
    options: {
        pan: {
            enabled: true,
            mode: 'xy',
            rangeMin: {
                x: -10, y: 0
            },
            rangeMax: {
                x: 10, y: 10
            }
        },
        zoom: {
            enabled: true,
            mode: 'xy',
        }
    },
});
```

This code on CodePen https://codepen.io/anon/pen/ZPGyEK

I attach diff file with solving this problem [chart.zoom.js.diff.zip](https://github.com/chartjs/chartjs-plugin-zoom/files/2910517/chart.zoom.js.diff.zip)

**Comment by benmccann** [comment] 2019-03-01 22:13
This looks like a duplicate of https://github.com/chartjs/chartjs-plugin-zoom/issues/140

**Closed by benmccann** 2019-03-01 22:13 UTC
