### ISSUE TITLE
Category scale pans while zooming

### ISSUE THREAD

**Issue by benmccann** [chartjs/chartjs-plugin-zoom#190] opened 2019-01-17 16:01 UTC
In samples/zoom-bar-x.html, my mouse is not remaining the focal point. First zoom all the way out on this sample first to show more data on the chart. Now let go and start a new zoom inward. I'd expect the date that my mouse is hovering over to remain under my mouse. Instead it starts moving sideways

**Comment by jledentu** [comment] 2019-01-23 13:11
@benmccann Mmh I think it's difficult to develop this behaviour on `category` scales. Currently, when we zoom in the chart:
- we increment the min index (if the cursor is `>=` the center of the chart)
- we decrement the max index (if the cursor is `<` the center)

So by changing the index we simply remove a whole category (that's why the zoom is not precise). I don't think chart.js allows to draw a category partially?

**Comment by benmccann** [comment] 2019-01-23 17:10
Hmm. Good point. If the cursor 60% of the distance from left to right then I think we'd want to remove a category on the left 60% of the time and on the right 40% of the time. Right now we do it on the left 100% of the time.

I'm not sure what a good way to fix this is or if it's worth doing. Maybe we could keep track of the starting category and see which zoom is more likely to keep it under the mouse?

**Comment by jledentu** [comment] 2020-01-14 12:58
Maybe it would be simpler to zoom in uniformly (and not depending on the position of the mouse), link in this example? https://demos.telerik.com/kendo-ui/bar-charts/pan-and-zoom

**Comment by etimberg** [comment] 2021-04-25 16:06
Duplicate of #151

**Closed by etimberg** 2021-04-25 16:06 UTC
