### ISSUE TITLE
Stop zooming in point

### ISSUE THREAD

**Issue by hstemplewski** [chartjs/chartjs-plugin-zoom#299] opened 2019-11-25 15:20 UTC
Hi, i'd like to set some breakpoint to stop zooming when Y and X go to some values. 
Current behaviour: when i set Y min to 10
![image](https://user-images.githubusercontent.com/25898331/69552755-51835680-0f9f-11ea-851a-99d21cc567ac.png)
Expected bahaviour: 
Stop (block) zooming when Y value go to range form 0 to 10
![image](https://user-images.githubusercontent.com/25898331/69552811-65c75380-0f9f-11ea-9bc3-09ce59bb941d.png)

**Comment by etimberg** [comment] 2021-04-25 16:35
Duplicate of #112

**Closed by etimberg** 2021-04-25 16:35 UTC
Labels: duplicate, enhancement
