### ISSUE TITLE
zoom drill down limit

### ISSUE THREAD

**Issue by sabres207** [chartjs/chartjs-plugin-zoom#413] opened 2020-12-24 15:56 UTC
Hey everyone,
I want to limit my chart zoom drill down not to be infinite.
Currently, I can zoom in more and more forever, and I would like the zoom to stop when the chart is displaying 1 or 2 data points, instead of drilling in forever and just showing a flat line.

I tried the rangeMin and rangeMax, but it seems like the control only the min and max labels on the xAxis, but not the min and max scaling.

my current config:
        zoom: {
          enabled: true,
          mode: 'x',
          threshold: 10,
          rangeMin: {
            x: timeLabels[0],
          },
          rangeMax: {
            x: timeLabels[timeLabels.length - 1],
          },
        },
        pan: {
          enabled: true,
          mode: 'x',
          rangeMin: {
            x: timeLabels[0],
          },
          rangeMax: {
            x: timeLabels[timeLabels.length - 1],
          },
        },

**Comment by ankypant** [comment] 2021-03-15 19:36
Hello, @sabres207 did you figure out a solution for this?

**Comment by etimberg** [comment] 2021-04-25 17:34
Duplicate of #112

**Closed by etimberg** 2021-04-25 17:34 UTC
Labels: enhancement
