### ISSUE TITLE
Django : chartjs-plugin-zoom not working

### ISSUE THREAD

**Issue by pawan7476** [chartjs/chartjs-plugin-zoom#302] opened 2019-11-28 11:50 UTC
I'm trying to integrate chartjs-plugin-zoom plugin with my canvas in my django application .I'm getting dataset values from backend API .Canvas is rendered but pan and zoom is not working . There is no error on the console.

```
<script>
{% block jquery %}
var endpoint = 'perf-chart'
var cps = []
var overall_process_mem = []
var average = []
var overall_process_core = []
var updatedCPS = []
var updatedMEM = []
var  updatedDISK = []
var  updatedCPU = []   
var memory = []
var cpu_all = []
var labels = []
var mem_used = []
var cpu_all = []
var labels = []


$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        updatedCPS = data.updatedCPS
        updatedMEM = data.updatedMEM
        updatedDISK = data.updatedDISK
        updatedCPU = data.updatedCPU
        overall_process_core = data.overall_process_core
        overall_process_mem = data.overall_process_mem
        core_list_updated = data.core_list_updated
        average = data.average
        cps = data.cps
        cpu_all = data.cpu_all
        disk_io = data.disk_io
        memory = data.memory
        percentile = data.percentile
        error_msg = data.error_msg
        caution = data.caution
        if (error_msg)
            alert(caution);
        else
            setChart();


    },
    error: function(error_data){
        //console.log("error")
        //console.log(error_data)
        alert(error_data.status);
        alert(error_data.error);
    }
})



function setChart(){
    var ctx = document.getElementById('myChart')

try {
    var average = (array) => array.reduce((a, b) => a + b, 0) / array.length;
}
catch(err) {
    average = "Garbage Value"
}
const asc = arr => arr.sort((a, b) => a - b);

const quantile = (arr, q) => {
    const sorted = asc(arr);
    const pos = ((sorted.length) - 1) * q;
    const base = Math.floor(pos);
    const rest = pos - base;
    if ((sorted[base + 1] !== undefined)) {
        return sorted[base] + rest * (sorted[base + 1] - sorted[base]);
    } else {
        return sorted[base];
    }
};




    
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'CPU [avg:'+average(updatedCPU).toFixed(2)+'; min:'+Math.min.apply(null, updatedCPU)+'; max:'+Math.max.apply(null, updatedCPU)+'; {'+percentile+' percentile :'+quantile(updatedCPU, percentile/100).toFixed(2)+' }]',
                    data: updated_cpu,
                    backgroundColor: [

                'rgba(153, 102, 255, 0.2)'

            ],
            borderColor: [

                'rgba(153, 102, 255, 1)'

            ],
            borderWidth: 2,
                    fill: false
                },{
                    label: 'CPS [avg:'+average(updatedCPS).toFixed(2)+'; min:'+Math.min.apply(null, updatedCPS)+'; max:'+Math.max.apply(null, updatedCPS)+'; {'+percentile+' percentile :'+quantile(updatedCPS, percentile/100)+' }]',
                    data: updated_cps,
                    yAxisID: 'A',
                    backgroundColor: [

                'rgba(153, 1190, 255, 0.2)'

            ],
            borderColor: [

                'rgba(153, 1190, 255, 1)'

            ],
            borderWidth: 2
                },{
                    label: 'Memory [avg:'+average(updatedMEM).toFixed(2)+'; min:'+Math.min.apply(null, updatedMEM)+'; max:'+Math.max.apply(null, updatedMEM)+'; {'+percentile+' percentile :'+quantile(updatedMEM, percentile/100).toFixed(2)+' }]',
                    data: updated_mem,
                    backgroundColor: [

                'rgba(255, 99, 132, 0.2)'

            ],
            borderColor: [

                'rgba(255, 99, 132, 1)'

            ],
            borderWidth: 2,
                    fill: false
                }]
            },
    options: {
        title: {
            display: true,
            text: 'PERFAnalyzer',
            fontColor: '#666'
        },
        zoomEnabled: true,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                },
                scaleLabel: {
                     display: true,
                     labelString: 'CPU - Memory',
                     fontSize: 12
                  }
            }, {
                id: 'A',
                type: 'linear',
                position: 'right',
                ticks: {

          min: 0
        },
                scaleLabel: {
                     display: true,
                     labelString: 'CPS',
                     fontSize: 12
                  }

            }
            ],
            xAxes: [{
                ticks: {
                    beginAtZero: false,
                },
                scaleLabel: {
                     display: true,
                     labelString: 'Date-Time',
                     fontSize: 15
                  }
            }]
        },
       plugins: {
						zoom: {
							pan: {
								enabled: true,
								mode: 'x'
							},
							zoom: {
								enabled: true,
                                //drag: true,
								mode: 'x',
                                speed: 0.1,
							}
						}
					}
    }
        })

    
}




{% endblock %}


</script>

{% block content %}
<button type="button" class="btn btn-info collapsed" data-toggle="collapse" data-target="#demo0" >CPU/Mem</button>
<div class="container">
<div id="demo0" class="collapse">
    <div class='row'>
    <div class='col-sm-12' >

        <div class='col-' id="chart-container" class="myChartDiv">
            <canvas id="myChart" width="600" height="400"></canvas>
        </div>
    </div>
    </div>
<br>
    </div>
</div>
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.1"></script> 
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script> 
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@0.7.4"></script>

----------------------------------------------------------------------------------------------------------
Please find the sample rendered canvas for your reference @benmccann 
![cpu-mem](https://user-images.githubusercontent.com/52998517/69846455-17b19900-129a-11ea-8a86-312033b39cfe.JPG)

**Comment by benmccann** [comment] 2019-11-28 15:53
Your code is too hard to read since it's all on one line. Can you please properly format it?

**Comment by jledentu** [comment] 2019-11-28 20:13
@benmccann I think this is one more issue about the category scale, which is apparently not handled correctly? See #8 #86 #296. I plan to get a look into this in the coming days.

**Comment by pawan7476** [comment] 2019-11-29 05:51
@benmccann I've updated the comment code with proper formatted rendered code.

**Comment by jledentu** [comment] 2020-01-14 09:14
@pawan7476 Could you provide a minimal reproducible example in a Codepen, jsfiddle or something? Your code is not executable as is.

**Comment by etimberg** [comment] 2021-04-25 16:46
Closing due to lack of test case

**Closed by etimberg** 2021-04-25 16:46 UTC
Labels: needs test case
