### ISSUE TITLE
Explictly make Hammer.js a dependency or document that it must be included beforehand

### ISSUE THREAD

**Issue by stece** [chartjs/chartjs-plugin-zoom#156] opened 2018-07-01 16:25 UTC
I'm having an issue with panning.

Looking at the provided code example https://codepen.io/anon/pen/PGabEK Click&Drag does not pan the chart. Zooming works, but panning doesn't.

Using Chrome version 67.0.3396.99

**Comment by stece** [comment] 2018-07-04 18:35
I was using the latest version of chart.js 2.7.x. I now also tried with the version 2.6.0 but I have the same problem. I tried this just to be sure. 

But in the end the sample also doesn't work for panning.

**Comment by Charles-Isaac** [comment] 2018-07-31 14:31
I could reproduce the bug on every major browser (chrome, firefox, edge, explorer, opera... etc)

**Comment by buhlerjohnendicott** [comment] 2018-08-01 12:28
Agreed, also having struggles to get pan to work in Chrome with provided demo...

**Comment by DenisSa** [comment] 2018-08-14 18:28
Trying including hammer.js before chartjs and chartjs zoom plugin.

**Comment by buhlerjohnendicott** [comment] 2018-08-15 11:44
@DenisSa hammer.js worked for me here as well! I forked @stece pen, added hammer.js, and you can see it working here: https://codepen.io/anon/pen/gjJGze

**Comment by erwinverdonk** [comment] 2018-09-26 10:35
Its a bug that appear in all browsers. For what I can see it is related to how data is provided. When the data and labels are provided in arrays like in the example it does not work. When it is provided with the X and Y variables it does appear to work. Sorry no example here, just analysed the examples that work and dont work.

**Comment by mlangwell** [comment] 2018-10-16 18:24
@DenisSa solution worked for me as well. This issue should be closed, thanks!

**Comment by DenisSa** [comment] 2018-10-16 18:49
Imo they should include hammer.js as a dependency for this plugin before closing the issue. Otherwise people will keep asking the same question.

**Comment by dende** [comment] 2019-02-07 12:00
Push, I was very confused for the last days, because pannig did not work. The little note that Hammer js is required for gesture recognition was not clear enough for me since it was not included in the codepen example.

**Comment by jledentu** [comment] 2019-02-07 12:40
https://github.com/chartjs/chartjs-plugin-zoom/pull/193 has fixed the issue, so hammerjs will be included in the next release.

**Closed** 2019-02-07 12:41 UTC
