### ISSUE TITLE
[BUG] Issue with resetZoom method!!

### ISSUE THREAD

**Issue by AhmedBHameed** [chartjs/chartjs-plugin-zoom#100] opened 2017-08-27 01:48 UTC
IMPORTANT!!!
Some times when i use resetZoom method i get this error Exception "Cannot read property 'getPixelForValue' of undefined"
It is random to happen not a fixed error so i could not specify the error place or the code!!!
But it happened when i use default zoom for the liner chart.

This bug causes the chart to stop iteration so it is an important issue must be solved.

Below is my configuration but still the error occur randomly!

```
this.configuration = {
        type: 'line',
        data: {
          labels: config.labels,
          datasets: config.datasets || [window.randomScalingFactor(), window.randomScalingFactor(), window.randomScalingFactor()]
        },
        options: {
          responsive: true,
          title: {
            display: true,
            text: config.chartTitle || 'Liner Chart Measurement'
          },
          tooltips: {
            mode: 'index',
            intersect: false,
          },
          hover: {
            mode: 'nearest',
            intersect: true
          },
          scales: {
            xAxes: [{
              // Specific to Bar Controller
              categoryPercentage: 0.8,
              barPercentage: 0.9,

              // grid line settings
              gridLines: {
                  offsetGridLines: false
              },
              scaleLabel: {
                display: true,
                labelString: 'Month'
              }
            }],
            yAxes: [{
              display: true,
              stacked: false,
              scaleLabel: {
                display: true,
                labelString: 'Value'
              },
              ticks: {
                min: config.min || 0,
                max: config.max || 100,
                // forces step size to be 5 units
                stepSize: config.YStepSize || 5
              }
            }]
          },
          // Container for pan options
          pan: {
            // Boolean to enable panning
            enabled: true,

            // Panning directions. Remove the appropriate direction to disable 
            // Eg. 'y' would only allow panning in the y direction
            mode: config.zoom || 'xy'
          },

          // Container for zoom options
          zoom: {
            // Boolean to enable zooming
            enabled: true,

            // Zooming directions. Remove the appropriate direction to disable 
            // Eg. 'y' would only allow zooming in the y direction
            mode: config.zoom || 'xy',
          }
        }
      }; 
```

**Comment by etimberg** [comment] 2021-04-25 15:54
Closing since this is quite old and large portions of this have been rewritten for 1.0.0-beta.1. Please reopen if there's a fiddle that reproduces this

**Closed by etimberg** 2021-04-25 15:54 UTC
Labels: bug
