### ISSUE TITLE
Zoom In & Out Buttons

### ISSUE THREAD

**Issue by ravau** [chartjs/chartjs-plugin-zoom#242] opened 2019-06-07 16:13 UTC
Want a zoom activity with buttons with onclick. Other issues does not work successfully. Anyone managed to do that already?

**Comment by benmccann** [comment] 2019-06-07 16:21
Duplicate of https://github.com/chartjs/chartjs-plugin-zoom/issues/43

**Closed by benmccann** 2019-06-07 16:21 UTC
