### ISSUE TITLE
Programmatically zoom

### ISSUE THREAD

**Issue by KoalaBear84** [chartjs/chartjs-plugin-zoom#444] opened 2021-04-06 08:15 UTC
Is there a way to zoom programmatically? Like "Zoom to last day"?

I ask this for the Chart.js 3 version.

**Comment by stockiNail** [comment] 2021-04-06 11:21
@KoalaBear84 maybe you should create an event and dispatch it.

When the plugin is enabled, the element used to get events by HammerJS is stored in `chartInstance.$zoom._node`.

```javascript
onMyZoom = function() {
  if (chartInstance.$zoom && chartInstance.$zoom._node) {
    const wheeleventLeft = new WheelEvent("wheel", { deltaX: -500 });
    chartInstance.$zoom._node.dispatchEvent(wheeleventLeft);
  }
}
```

**Comment by KoalaBear84** [comment] 2021-04-20 14:40
Thanks @stockiNail for your quick answer, and sorry for the late reply.

```javascript
yourchart.config.options.plugins.zoom.zoom.rangeMin.x = new Date('2021-04-19');
yourchart.config.options.plugins.zoom.zoom.rangeMax.x = new Date('2021-04-20');
yourchart.$zoom._node.dispatchEvent(new WheelEvent("wheel", { deltaX: 0, deltaY: 0, delta: 0 }))
```

This sort of works and was what I hoped be possible. The problem is that this is now a 'hard' limit and have to use `resetZoom` to 'exit'. Is there any other way? Also, when calling the event, it always moves, even though all delta's are 0.

Do you have idea's for these?

**Comment by etimberg** [comment] 2021-04-25 17:37
Duplicate of #82

**Closed** 2021-04-25 18:55 UTC
Labels: duplicate, enhancement
