### ISSUE TITLE
Make Hammer.js optional or clarify docs

### ISSUE THREAD

**Issue by pvfpvf** [chartjs/chartjs-plugin-zoom#174] opened 2018-10-16 15:43 UTC
I have boiled this down from a much bigger file. If you run this, click PLOT IT and then operate mouse wheel, it will zoom. But if you put mouse cursor within the plot, left click, and drag, nothing happens. It will not pan.

I can see little difference between this case and [this codepen](https://codepen.io/marcusvilete/pen/EEpKMx)
except that I have no labels.

What am I doing wrong please?

I have not used codepen because of earlier statements that it affected this kind of issue. But please see my zip.
[test3.zip](https://github.com/chartjs/chartjs-plugin-zoom/files/2483836/test3.zip)

Note: I have edited line 14295 of Chart.js, but do not think that is relevant.

**Comment by pvfpvf** [comment] 2018-10-22 19:31
I'd appreciate some help on this.

**Comment by benmccann** [comment] 2019-01-24 04:45
Closing as duplicate of https://github.com/chartjs/chartjs-plugin-zoom/issues/156

**Closed by benmccann** 2019-01-24 04:45 UTC
