### ISSUE TITLE
problem migration to  Chart.js 3.0 with zoom plugin

### ISSUE THREAD

**Issue by sabres207** [chartjs/chartjs-plugin-zoom#516] opened 2021-05-20 06:59 UTC
You mention that this plugin is for Chart.js 3.0, and if using previous version of Chart.js, version 0.7.7 of this plugin should be used.
But - the latest version of this plugin IS 0.7.7.

And when I try to use this 0.7.7 latest version after migrating to Chart.js 3.0 I get the following error:
`Uncaught TypeError: Cannot read property 'plugins' of undefined`
Which is caused by this line:
Chart.Zoom.defaults = Chart.defaults.global.plugins.zoom...

Any helpful advice regarding migration to Chart.js 3.0 using the zoom plugin would be super appreciated.
Thanks!

**Comment by sushmit-telaverge** [comment] 2021-05-20 07:01
![image](https://user-images.githubusercontent.com/77407027/118933756-382a5300-b967-11eb-8c39-29236884bc85.png)

Uncaught TypeError: Cannot read property 'plugins' of undefined

**Comment by stockiNail** [comment] 2021-05-20 07:25
@sabres207 @sushmit-telaverge the latest stable version is 0.7.7 but it works ONLY with CHART 2.
Therefore if you are using zoom plugin 0.7.7 on Chart.js 3, it doesn't work.

With Chart.js 3, you could use https://github.com/chartjs/chartjs-plugin-zoom/releases/tag/v1.0.0-rc.

JSDELIVR https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@1.0.0-rc/dist/chartjs-plugin-zoom.min.js

**Comment by sabres207** [comment] 2021-05-20 08:24
@stockiNail Thank you!
Would be very helpful to point it out somewhere in the README.

**Comment by stockiNail** [comment] 2021-05-20 08:54
@sabres207 updated readme in my fork.

Have a look to [README](https://github.com/pepstock-org/chartjs-plugin-zoom/tree/changeReadme#chartjs-plugin-zoom) if it's ok for you. If ok, I'll submit PR.

**Comment by kurkle** [comment] 2021-05-20 08:57
Duplicate of #491

**Comment by stockiNail** [comment] 2021-05-20 09:54
@kurkle Thanks a lot! I missed it. Anyway I think not all users go to static documentation and many of them stay on readme page.

**Comment by kurkle** [comment] 2021-05-20 10:02
I agree the readme is written like v1 was already released. It describes the master branch accurately though.

I still agree stand behind the comment I posted in there:

> Further documentaion about the need for beta is just not there, because we are still in the time/space of chart.js v3 beta releases and just fallen a little behind with a full release. You can expect it soon, and thus I'm not in favor of documenting the current state.

RC has been out 3 days. I think it can be released as v1 if no blocking issues are found this week.

**Closed** 2021-05-24 07:28 UTC
