### ISSUE TITLE
Datetime axes with range limit is not zooming

### ISSUE THREAD

**Issue by anton-shchyrov** [chartjs/chartjs-plugin-zoom#213] opened 2019-03-04 13:38 UTC
```
function addHour(date, val) {
  const res = new Date(date.valueOf() + val * 1000 * 60 * 60);
  return res;
}

const startDate = new Date("2019-03-04 12:00:00");

new Chart(document.getElementById("chart"), {
  type: "scatter",
  data: {
    datasets: [
      {
        label: "Test",
        showLine: true,
        data: [
          {
            x: startDate,
            y: 0
          },
          {
            x: addHour(startDate, 1),
            y: 10
          },
          {
            x: addHour(startDate, 2),
            y: 5
          }
        ]
      }
    ]
  },
  options: {
    scales: {
      xAxes: [
        {
          type: "time",
        }
      ]
    },
    zoom: {
      enabled: true,
      mode: "xy",
      rangeMin: {
        x: startDate,
        y: 0
      },
      rangeMax: {
        x: addHour(startDate, 2),
        y: 10
      }
    }
  }
});

```

Code pen code https://codepen.io/anon/pen/xBOBvr

Without rangeMin and rangeMax all is well

Maybe instead

```
function zoomTimeScale(scale, zoom, center, zoomOptions) {
        ...............
	var newMin = scale.getValueForPixel(scale.getPixelForValue(scale.min) + minDelta);
	var newMax = scale.getValueForPixel(scale.getPixelForValue(scale.max) - maxDelta);

	var diffMinMax = newMax.diff(newMin);
	var minLimitExceeded = rangeMinLimiter(zoomOptions, diffMinMax) != diffMinMax;
	var maxLimitExceeded = rangeMaxLimiter(zoomOptions, diffMinMax) != diffMinMax;

	if (!minLimitExceeded || !maxLimitExceeded) {
		options.time.min = newMin;
		options.time.max = newMax;
	}
}

```
should be

```
function zoomTimeScale(scale, zoom, center, zoomOptions) {
        ...............
	var newMin = scale.getValueForPixel(scale.getPixelForValue(scale.min) + minDelta);
	var newMax = scale.getValueForPixel(scale.getPixelForValue(scale.max) - maxDelta);

	options.time.min = rangeMinLimiter(zoomOptions, newMin);
	options.time.max = rangeMaxLimiter(zoomOptions, newMax);
}

```
?

**Comment by benmccann** [comment] 2019-03-04 15:17
Duplicate of https://github.com/chartjs/chartjs-plugin-zoom/issues/187. There's a pending PR to fix this issue

**Closed by benmccann** 2019-03-04 15:17 UTC
