### ISSUE TITLE
Chart doesn't update when zoom: min property has changed

### ISSUE THREAD

**Issue by joseRelvasF3m** [chartjs/chartjs-plugin-zoom#228] opened 2019-03-27 11:00 UTC
First things first, I'm working in Angular 7 and I got the following "app":
![grafico_zoom](https://user-images.githubusercontent.com/46492808/55068755-7a52f500-507a-11e9-8ab0-7cebd327263f.png)

The top bar is a date filter, that gives the opportunity to choose the day "From" (De in portuguese) and the day "To" (Até in portuguese). It is supposed, by choosing these days, the graphic show only  the respective interval, for example: day 2019/01/01 to 2019/02/02. Simple as that. So now I will show the logic I use to pass the data from the the bar component (`filtro-data.component`) to the parent (`charts-report.component`), and then from the parent to many graphics, but for now we only will use the (`dimensao-component`). I'm only working with de From input to give it to the zoom: min.

`filtro-data. component.ts`
```

export class FiltroDataComponent implements OnInit {

  dateDe : any;
  dateAte : any;
  
  @Output() dateDeEvent = new EventEmitter<string>()

  constructor() { }

  ngOnInit() { }

  sendMessage() {
    this.dateDeEvent.emit(this.dateDe);
  }
}

```
`filtro-data.component.html`

```
<input id="dateDe" name="dateDe" [(ngModel)]="dateDe" type="date" required>
 <input type="date" id="dateAte" name="dateAte" [(ngModel)]="dateAte" required>
<button (click) = "sendMessage()">Aplicar</button>
```
So here I preparred the data from the inputs to send them to the parent. Here's the parent:

`charts-report.component.ts`

```
export class ChartsReportComponent implements OnInit {
  @ViewChild(DimensaoComponent) dimensaoC: DimensaoComponent; //to import the component dimensao

  constructor(private formbulider: FormBuilder, private route: ActivatedRoute) {  }

  dateDe: any;

  receiveMessage($event) {
    this.dateDe = $event;
    this.dimensaoC.updateChart() //this will make sense
  }

  ngOnInit() {}
}
```
`charts-report.component.html`

```
<app-filtro-data (dateDeEvent)="receiveMessage($event)"></app-filtro-data>
 <app-dimensao [dateDe]="dateDe"></app-dimensao>
```
With all of this I will send the information to my component dimensao... 

`dimensao.component.ts`

`  @Input() dateDe : any;`

```
(...)
        time: {
            unit: 'day',
            min: this.dateDe
        }
(...)
   updateChart(){
    this.LineChart.update();
  }   
```
I did some "tests" and the `dimensao component` receive the date I choose in the filter-date.component, so it's all good...but then the graphic doesn't update when I click in the button "Aplicar", even with the function to do it (see receiveMessage in charts-report.component)... I've tried many things, but nothing work it out. Do you know what I could do? I just want the graphic to update with the new  data in "min". Thank you.

**Comment by benmccann** [comment] 2019-03-27 15:39
You don't need the zoom plugin for this. The zoom plugin is used to zoom when the user interacts with the chart such as scrolling the middle button or dragging a box over the chart. But if you're setting the min and max directly as in this case then I would recommend you do that without using this plugin to make things simpler.

I'm not sure what the issue is with your case and am not familiar with Angular. I'm going to close this since it's really not related to the plugin and I think you'll be better off not using the plugin for this feature.

**Closed by benmccann** 2019-03-27 15:39 UTC

**Comment by joseRelvasF3m** [comment] 2019-03-27 15:45
@benmccann I think is related, because I want to update the chart, and the zoom: min it's not answering to the value I passed... there's nothing to do with angular. Thank you by the way.

**Comment by RafaelVieira2323** [comment] 2019-03-27 16:20
@joseRelvasF3m  i have the same issue.

**Comment by jledentu** [comment] 2019-03-28 07:47
@joseRelvasF3m @RafaelVieira2323 Can you reproduce and share this issue in a CodePen/JSBin? The code you show doesn't contain anything related to this plugin.

**Comment by benmccann** [comment] 2019-03-29 20:21
@joseRelvasF3m you shouldn't set zoom: min. Do this instead: https://github.com/chartjs/chartjs-plugin-zoom/issues/126#issuecomment-477409568
