### ISSUE TITLE
duplicated labels break zoom and pan

### ISSUE THREAD

**Issue by chrisywebsite** [chartjs/chartjs-plugin-zoom#369] opened 2020-06-23 04:48 UTC
Hey, 
I'm using this zoom plugin to display data, which is grouped by dates. I find the 'zoom' function will 'jump' to the minimum zoom level when it is zoomed out to the maximum. So does the 'pan' function. 

It is related to duplicated labels on my x axis, which is like [May 01, 02, ... 31, Jun 01, 02, ...]. The labels repeat themselves each month. I find zoom and pan work fine under circumstances where labels have no duplicates, e.g. [1, 2, 3, .... n, n + 1, ...] . 
Test data: 
`var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ["1", "2", "3", "4", "5", "6", "1", "2", "3", "4", "5", "6"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3, 12, 19, 3, 5, 2, 3]
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        },
        plugins: {
            zoom: {
                // Container for pan options
                pan: {
                    // Boolean to enable panning
                    enabled: true,

                    // Panning directions. Remove the appropriate direction to disable 
                    // Eg. 'y' would only allow panning in the y direction
                    mode: 'x'
                },

                // Container for zoom options
                zoom: {
                    // Boolean to enable zooming
                    enabled: true,

                    // Zooming directions. Remove the appropriate direction to disable 
                    // Eg. 'y' would only allow zooming in the y direction
                    mode: 'x',
                }
            }
        }
    }
});`

A workaround can be using full date like 2020-May-01 but it would be too crowded or stacked up sometimes. 

So I just wonder if there is a solution to this requirement that there are duplicates in labels. 

versions: 
    "chart.js": "^2.9.3",
    "chartjs-plugin-annotation": "^0.5.7",
    "chartjs-plugin-zoom": "^0.7.7",

**Comment by etimberg** [comment] 2021-04-25 17:26
Duplicate of #139

**Closed by etimberg** 2021-04-25 17:26 UTC
