### ISSUE TITLE
Document Hammer JS requirement for panning

### ISSUE THREAD

**Issue by neon-dev** [chartjs/chartjs-plugin-zoom#133] opened 2018-04-16 11:22 UTC
If you include this plugin locally or via cdn, you won't notice something isn't working until you try to pan for the first time.
The hammer.js is dependency is neither explicitly stated in the documentation, nor will you get a console error. I'd suggest to implement both (the console message only if `pan.enabled` is set to `true`).

**Comment by benmccann** [comment] 2019-01-24 04:49
Closing as duplicate of https://github.com/chartjs/chartjs-plugin-zoom/issues/156

**Closed by benmccann** 2019-01-24 04:49 UTC
