### ISSUE TITLE
Zoom drag doesn't work with x-axis

### ISSUE THREAD

**Issue by AliBasicCoder** [chartjs/chartjs-plugin-zoom#355] opened 2020-05-12 05:45 UTC
hi,

so i when i try to zoom using drag it doesn't work

and i checked if the plugin is loaded and it is

and no messages are printed  to the console

and when set mode to ```xy``` it only zooms in the y axis 

my config
```js
{
    type: "bar",
    data: {
      labels,
      datasets: [
        {
          label: "Download",
          backgroundColor: /* ... */,
          data: /* ... */,
        },
        {
          label: "Upload",
          backgroundColor: /* ... */,
          data: /* ... */,
        },
        {
          label: "Total",
          backgroundColor: /* ... */,
          data: /* ... */,
        },
      ],
    },
    options: {
      legend: {
        display: true,
        position: "right",
      },
      scales: {
        yAxes: [
          {
            ticks: {
              callback: (value: string) => /* ... */,
            },
          },
        ],
      },
      tooltips: {
        callbacks: {
          label(tooltip: { value: string }) {
            /* ... */
          },
        },
      },
      plugins: {
        zoom: {
          zoom: {
            enabled: true,
            drag: true,
            mode: "x",
            onZoom() {
              /* ... */
            },
          },
        },
      },
    },
 };
```

**Comment by yoelz55** [comment] 2020-05-12 06:24
Hi, I have exactly the same issue, it seems that there is a problem with the x-axis with numerical type, when I tried the demo of this package, the zoom in x-axis works perfectly because the type of the x-axis is date.

**Comment by benedekt** [comment] 2020-05-27 11:28
I had the same problem, and solved it by upgrading to ChartJS 2.9.1!
Try to update if yours is outdated, it might help.

**Comment by borjaseijo** [comment] 2020-06-03 15:04
> I had the same problem, and solved it by upgrading to ChartJS 2.9.1!
> Try to update if yours is outdated, it might help.

I have tried to solve my issue with this answer, but the zoom problem continues. I think that there is a bug in the plugin.

**Comment by AliBasicCoder** [comment] 2020-06-04 14:20
> I had the same problem, and solved it by upgrading to ChartJS 2.9.1!
> Try to update if yours is outdated, it might help.

i tried it with v2.9.1 and v2.9.3 and it didn't work

**Comment by ankworld** [comment] 2020-06-05 08:34
> Hi, I have exactly the same issue, it seems that there is a problem with the x-axis with numerical type, when I tried the demo of this package, the zoom in x-axis works perfectly because the type of the x-axis is date.

You're right. It works when the x-axis is the date. This should be bugs or not support feature.

**Comment by BlueEther** [comment] 2020-06-11 05:38
Yep, I seem to have it this as well on 0.7.7 with date/time x axis (yyy-mm-ddThh:mm:ssZ)

using 0.7.4 will allow the zoom to work

**Comment by benmccann** [comment] 2020-06-11 12:47
@BlueEther can you test if 0.7.5 or 0.7.6 will work? It'd be nice to narrow down where the regression might have entered

**Comment by borjaseijo** [comment] 2020-06-12 07:58
I have tested with the 0.7.4 and the zoom continues to fail.
I am using the following source to generate the final chart where x-axis contains dates that use the format _dd-mm-yyyy_:
```
    return new Chart(chart, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                lineTension: 0.3,
                backgroundColor: "rgba(78, 115, 223, 0.05)",
                borderColor: "rgba(78, 115, 223, 1)",
                pointRadius: 3,
                pointBackgroundColor: "rgba(78, 115, 223, 1)",
                pointBorderColor: "rgba(78, 115, 223, 1)",
                pointHoverRadius: 3,
                pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
                pointHoverBorderColor: "rgba(78, 115, 223, 1)",
                pointHitRadius: 10,
                pointBorderWidth: 2,
                label: labelName,
                data: data
            }]
        },
        options: {
            maintainAspectRatio: false,
            layout: {
                padding: {
                    left: 10,
                    right: 25,
                    top: 25,
                    bottom: 0
                }
            },
            scales: {
                xAxes: [{
                    time: {
                        unit: 'date'
                    },
                    gridLines: {
                        display: false,
                        drawBorder: false
                    },
                    ticks: {
                        maxTicksLimit: 7
                    }
                }],
                yAxes: [{
                    ticks: {
                        maxTicksLimit: 5,
                        padding: 10,
                    },
                    gridLines: {
                        color: "rgb(234, 236, 244)",
                        zeroLineColor: "rgb(234, 236, 244)",
                        drawBorder: false,
                        borderDash: [2],
                        zeroLineBorderDash: [2]
                    }
                }]
            },
            legend: {
                display: false
            },
            tooltips: {
                backgroundColor: "rgb(255,255,255)",
                bodyFontColor: "#858796",
                titleMarginBottom: 10,
                titleFontColor: '#6e707e',
                titleFontSize: 14,
                borderColor: '#dddfeb',
                borderWidth: 1,
                xPadding: 15,
                yPadding: 15,
                displayColors: false,
                intersect: false,
                mode: 'index',
                caretPadding: 10
            },
            plugins: {
                zoom: {
                    // Container for pan options
                    pan: {
                        // Boolean to enable panning
                        enabled: true,
                        mode: 'x'
                    },
                    // Container for zoom options
                    zoom: {
                        enabled: true,
                        drag: {
                         	 animationDuration: 1000
                        },
                        mode: 'x'
                    }
                }
            }
        }
    });
```

**Comment by DjovDev** [comment] 2020-06-17 13:57
I have 1440 points on an X-Acis (24 hours in minutes), all formatted as HH:mm.

I can zoom perfectly on the Y axis, the X-axis does zoom but extremely slow, like 5 minutes per scroll.

**Comment by dmitrygalperin** [comment] 2020-07-21 21:13
I'm also having the same issue on the X axis with lots of datapoints. Drag does not work at all (it zooms, but only sometimes, and never accurately) and scroll zoom is extremely slow no matter what set the speed to.

**Comment by kurkle** [comment] 2021-05-16 06:07
Closing. We have working samples of drag-to-zoom with different scale types.

**Closed by kurkle** 2021-05-16 06:07 UTC
Labels: chart.js v2, needs test case
