### ISSUE TITLE
Zoom with Chartjs V7.0 doesn't work

### ISSUE THREAD

**Issue by ybarbaria** [chartjs/chartjs-plugin-zoom#110] opened 2017-10-17 14:35 UTC
Hello, I try to use the plugin with chartjs v7.0 but there is some issues when I use it. I made jsfiddle ; https://jsfiddle.net/YvanBarbaria/epavmj87/3/

You can see when you try to move the mouse on the chartjs all the chart moove fast fast... I've try to change speed, the result was the same.  If someone know a solution (I don't whant to change the version of the chartjs). Thx !

**Comment by alessandroperetti** [comment] 2017-10-17 14:48
Hello Barbaria, 

I have the same problem.  The panning is moving fast and it shows only two values at the same time.

Have you tried to change the chartJs version?

**Comment by ybarbaria** [comment] 2017-10-17 14:53
Hello Alessandro, I try the v4 v5 v6 of chartjs, same result. I'm not sure if I use correctly the zoom. 
I want to zoom when the "drag" is finish and be able to move the pan after that..

**Comment by alessandroperetti** [comment] 2017-10-17 15:17
I understood. I have the same problem but the drag option is disabled for me. When I try to pan in the chart the pan zooms the chart until the zoom is between two points. Of course, I can move through the chart but if you have thousands of points is not reasonable to move between two points each step.

I am trying to understand the source code but is not easy and I have no so much time to do it.

**Comment by alessandroperetti** [comment] 2017-10-23 06:43
Hi Yvan,

did you solve the problem?

Alessandro.

**Comment by ybarbaria** [comment] 2017-10-23 08:11
Hi Alessandro, 
I didn't solve this problem. I didn't have time. But I find a stable state when I set the config like that : 
`options.pan = {
          enabled: true,
          mode: 'x'
        };
  options.zoom = {
          enabled: true,
          mode: 'x'
        };`

**Comment by alessandroperetti** [comment] 2017-10-23 10:04
OK, thank you. I will try as you suggested and I will tell you my result.

Alessandro.

*Name Surname: *Alessandro Peretti
*E-mail (1):* alessandro.peretti.unicam@gmail.com
*E-mail (2):*  alessandro.peretti@studenti.unicam.it
Fax: (+39)07331771201
*Mobile Phone:* (+39)3407652586


2017-10-23 10:11 GMT+02:00 Yvan Barbaria <notifications@github.com>:

**Comment by alessandroperetti** [comment] 2017-10-24 13:07
It seems it doesn't work form me your suggestion. If a use the panning I have the chart Zoomed between two points as well. I have no choice, I must change the source code of the plugin :(

**Comment by ybarbaria** [comment] 2017-10-25 07:10
Let me know if u find any solution in the source code. I will search too.

**Comment by ybarbaria** [comment] 2017-10-25 08:24
@alessandroperetti  Do you set the type of your axis x? When I try to set the type to 'linear' the zoom become crazy. I have to don't set the type if I whant it's works.

**Comment by alessandroperetti** [comment] 2017-10-25 08:42
Dear Yvan,

this is my configuration for the x-axis in chartJS:

*                                xAxes: [{*
*   autoSkip: true,*
*             // type: 'time',*

*   time: {*

*   unit: 'day'*
*    // displayFormats: {*
*    // 'millisecond': 'MMM DD',*
*    // 'second': 'MMM DD',*
*    // 'minute': 'MMM DD',*
*    // 'hour': 'MMM DD',*
*    // 'day': 'MMM DD',*
*    // 'week': 'MMM DD',*
*    // 'month': 'MMM DD',*
*    // 'quarter': 'MMM DD',*
*    // 'year': 'MMM DD'*
* // }*
*   },*
*   ticks: {*
* maxTicksLimit: 2*
*   }*
*     }]*

What do you mean? I have to comment *unit:'day' *as well?

Alessandro.




*Name Surname: *Alessandro Peretti
*E-mail (1):* alessandro.peretti.unicam@gmail.com
*E-mail (2):*  alessandro.peretti@studenti.unicam.it
Fax: (+39)07331771201
*Mobile Phone:* (+39)3407652586


2017-10-25 10:24 GMT+02:00 Yvan Barbaria <notifications@github.com>:

**Comment by benmccann** [comment] 2017-12-28 15:41
Duplicate of https://github.com/chartjs/chartjs-plugin-zoom/issues/90. PR with fix pending

**Comment by benmccann** [comment] 2017-12-29 18:38
PR with fix was merged

**Closed by benmccann** 2017-12-29 18:38 UTC
