### ISSUE TITLE
[BUG] Points on the edge get cut off when zoom library included

### ISSUE THREAD

**Issue by rajkumar-osm** [chartjs/chartjs-plugin-zoom#177] opened 2018-11-09 08:42 UTC
## Expected behavior
All points should be properly rendered on the map. In the first place, the plugin should not affect the charts that don't have zoom or pan enabled.
![image](https://user-images.githubusercontent.com/17409789/48251861-13190900-e429-11e8-8c80-acdee79c07f3.png)

## Current behavior
Points on the edges of the graph get cut off.
![image](https://user-images.githubusercontent.com/17409789/48251831-009ecf80-e429-11e8-8970-98e426eda48e.png)

## Steps to Reproduce
Here is a sample codepen that demonstrates the problem: https://codepen.io/anon/pen/MzyNgK

## Initial investigation
I don't know the cause of the issue, but when I remove the chartjs-zoom-plugin completely, it works.

## Environment
Chart.js version: 2.7.3
Chartjs-plugin-zoom version: 0.6.5
Browser name and version: Chrome [Version 70.0.3538.77 (Official Build) (64-bit)]
Link to your project: https://codepen.io/anon/pen/MzyNgK

**Comment by jdbdnz** [comment] 2019-01-22 20:14
I'm also experiencing this issue. I haven't yet found a solution but here's some notes from my research:

Issue https://github.com/chartjs/Chart.js/issues/4715 looks similar and was closed as a duplicate of https://github.com/chartjs/Chart.js/issues/4637 which was closed with OP claiming Chart.js 2.7.2 didn't have the same problem.

I can confirm this issue is still present on 2.7.2

If I find a solution I'll post it here.

**Comment by jledentu** [comment] 2019-01-23 11:11
I think that [this line](https://github.com/chartjs/chartjs-plugin-zoom/blob/e53ee6ebe05e807921681e6969f3b07b6181adf3/src/chart.zoom.js#L581) causes the issue:

```js
ctx.rect(chartArea.left, chartArea.top, chartArea.right - chartArea.left, chartArea.bottom - chartArea.top);
ctx.clip();
```

I don't know yet why this `clip` is done, it probably solves other issues.

**Comment by jdbdnz** [comment] 2019-01-23 20:38
Thanks @jledentu, that is the culprit. If I comment it out, I no longer experience the clipping. I can only speculate what it does, but I'm assuming something important so probably not a path forward.

`ctx.clip()` was introduced in https://github.com/chartjs/chartjs-plugin-zoom/commit/a2a6e934d580cf71964e97d8fc78c3b326d1f988 and I've left a comment asking its intention, but I can't reasonably expect anyone to remember code they wrote in 2016 😂 

Depending on the intention of the clip, it may be that `chartArea` is not what we should use for `ctx.react`.

If I use the canvas offset rather than `chartArea` is also solves the issue for me:
```
var canvas = chartInstance.canvas;
ctx.rect(canvas.offsetLeft, canvas.offsetTop, canvas.offsetWidth, canvas.offsetHeight);
ctx.clip();
```

My next step will be to look into `chartArea` to see how it is calculated (it seems to be the graph inside of the labels/axis, but not sure) and see if that gives me any leads as to why it is being used for clipping.

**Comment by SosthenG** [comment] 2019-05-09 09:01
I'm facing the same issue.
@jdbdnz solution didn't worked for me, it actually cutted my chart even more.
Commenting the clip line didn't worked either, when I do so, the lines of the chart are getting out of it on zoom:
![image](https://user-images.githubusercontent.com/22033159/57441019-6093f880-7249-11e9-95cf-7518d46fce51.png)
For now, adding `-20` after chartArea.top worked in my case but I'm sure it won't for everyone (and it's very ugly).
Does anyone have found a real fix?

**Comment by benmccann** [comment] 2019-06-20 17:45
@SosthenG can you share a plnkr or jsfiddle to help me reproduce the issue you're having? Commenting out that line seems to work with all the samples in this project, so I'm wondering what's different in your case

**Comment by SosthenG** [comment] 2019-07-08 13:53
> @SosthenG can you share a plnkr or jsfiddle to help me reproduce the issue you're having? Commenting out that line seems to work with all the samples in this project, so I'm wondering what's different in your case

Sorry it looks like it was working after all, I tried to create a fiddle but I was not able to reproduce either. I found out that my problem was caused by a custom chart type that I am using (multicolorLine), so I tried your solution in #249 and it works fine if I use the chartjs base type (line).

**Comment by benmccann** [comment] 2019-07-08 16:54
Awesome. Thanks!  I've merged the fix, so hopefully this should work in the next release.

**Closed by benmccann** 2019-07-08 16:54 UTC
Labels: bug

**Comment by rbb81** [comment] 2022-03-17 09:38
Good day @benmccann , I experience the issue when the chart is zoom

![image](https://user-images.githubusercontent.com/61752013/158780498-32b806b6-c627-43c4-8342-6ab07204be0d.png)

when zoom
![image](https://user-images.githubusercontent.com/61752013/158780747-bacd3cec-7509-48e9-ae1e-1d87d8395455.png)

I try it on the documentation (sample chart / usage)
[Chart JS Zoom document](https://www.chartjs.org/chartjs-plugin-zoom/latest/guide/usage.html)

**Comment by AlexGoMa** [comment] 2023-10-02 13:50
I am experiencing the same issue. The points that have the same value as min or max, are cut by half horizontally by x axis.
Looking at the documentation, it's even in the shown graph! : [https://www.chartjs.org/docs/latest/samples/scales/linear-min-max.html](https://www.chartjs.org/docs/latest/samples/scales/linear-min-max.html)
