### ISSUE TITLE
Class instances not handled properly in configuration

### ISSUE THREAD

**Issue by iddings** [chartjs/chartjs-plugin-zoom#354] opened 2020-05-11 13:29 UTC
Class instances are not handled properly when passed as a value within the configuration. They are stripped down to only their properties, and no methods are preserved.

Example:

```javascript
class MyConfigClass {
  
  constructor(parameter) {
    this._private_parameter = parameter;
  }
  
  getParameter() {
    return this._private_parameter;
  }
  
}

  
Chart.plugins.register({
  id: 'example',
  beforeInit: function(chartInstance, pluginOptions) {

    // expect: an instance of MyConfigClass
    // actual: { _private_parameter: 'a value' }
    console.log(pluginOptions);

  }
});

const chart = new Chart(document.querySelector("#chart"), {
  options: {
    plugins: {
      'example': new MyConfigClass("a value")
    }
  }
});
```
[CodePen](https://codepen.io/bryaniddings/pen/eYpMpVJ)

This appears to happen as a result of `helpers.merge` calls on the config object.

For a real world example of this issue, take `chartjs-adapter-luxon`. One should be able to pass an instance of `luxon.FixedOffset` to `chart.options.scales.xAxes[0].adapters.date.zone` (or any other time axis), instead, `helpers.merge` converts this instance of FixedOffset to something like `{ fixedOffset: -300 }`. When this is passed back to the date adapter, Luxon has no idea what to do with that, so the chart breaks (see chartjs/chartjs-adapter-luxon#18).

**Comment by benmccann** [comment] 2020-05-11 13:59
Can you file this at https://github.com/chartjs/Chart.js instead?

I'm closing this one since the issue isn't in the zoom plugin, but in the core library

**Closed by benmccann** 2020-05-11 13:59 UTC

**Comment by iddings** [comment] 2020-05-11 14:16
Apologies, I meant to submit to Chart.js repo. Still shaking off cobwebs after a long weekend.
