### ISSUE TITLE
First x-axis Element disappears on zoom-out.

### ISSUE THREAD

**Issue by codafish-gmbh** [chartjs/chartjs-plugin-zoom#323] opened 2020-02-14 15:02 UTC
Unfortunately, the first x-axis dataset disappears when you zoom out a graph after zooming in. We are using time as unit.

**Inital State**
<img width="736" alt="initial_state" src="https://user-images.githubusercontent.com/2080312/74683278-add5cb00-51c8-11ea-89d5-dfcc0c9365b9.png">

**After Zoom**
<img width="719" alt="after_zoom" src="https://user-images.githubusercontent.com/2080312/74683242-8da60c00-51c8-11ea-9c1b-3479b52931df.png">

**Options-Configuration**

```
      pan: {
        enabled: this.widget.widget.enableZoom,
        speed: 0.05,
        mode: 'x',
        rangeMin: {
          x: chartOptions['rangeMin']
        },
        rangeMax: {
          x: chartOptions['rangeMax']
        },
      },
      zoom: {
        enabled: this.widget.widget.enableZoom,
        speed: 0.05,
        mode: 'x',
        rangeMin: {
          x: chartOptions['rangeMin']
        },
        rangeMax: {
          x: chartOptions['rangeMax']
        },
      },
scales: {
        xAxes: [{
          type: 'time',
          offset: true,
          gridLines: {
            offsetGridLines: true
          },
          distribution: 'linear',
          time: {
            tooltipFormat: this.currentUser.localMask.dateFormat.toUpperCase(),
            unit: this.currentUnit,
            unitStepSize: 1,
            displayFormats: {
              hour: this.currentUser.localMask.chartJsHour,
              day: this.currentUser.localMask.chartJsDay,
              week: this.currentUser.localMask.chartJsWeek,
              month: this.currentUser.localMask.chartJsMonth
            }
          },
        }],
        yAxes: [{
          scaleLabel: {
            display: true,
            labelString: chartOptions['yAxisLabel']
          },
          ticks: {
            beginAtZero: true,
            callback: function (value, index, values) {
              return value.toString().replace('.', that.currentUser.localMask.groupingCharacter);
            }
          }
        },
        ],
      },
```

**Comment by jledentu** [comment] 2020-03-10 10:44
Hi, could you provide a codepen/jsfiddle to reproduce your issue?

**Comment by etimberg** [comment] 2021-04-25 16:51
Closing due to lack of test case

**Closed by etimberg** 2021-04-25 16:51 UTC
Labels: bug, needs test case
